import { useState } from 'react';
import { type NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { api } from 'utils/api';
import { Navbar } from 'components/Navbar';
import { CategoryEntry } from 'components/CategoryEntry';

// TODO: Use SSR
const Home: NextPage = () => {
  const [activeCategory, setActiveCategory] = useState<string>();
  const { isSuccess, data } = api.entities.getCategories.useQuery(undefined, {
    staleTime: Infinity,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {isSuccess ? (
        <>
          <header className='flex px-4 py-3'>
            <Image
              className='mr-3'
              src='logo.svg'
              width={26}
              height={26}
              alt='Logo'
            />
            <h1 className='space-x-5 text-lg font-bold tracking-wider'>
              NEXT PIZZA
            </h1>
          </header>
          <Navbar
            activeLink={activeCategory}
            links={data
              .filter(({ listed }) => listed)
              .map(({ categoryName }) => categoryName)}
          />
          <main className='px-4'>
            {data.map((category) =>
              category.listed ? (
                <CategoryEntry
                  key={category.id}
                  id={category.id}
                  title={category.categoryName}
                  setActiveCategory={setActiveCategory}
                />
              ) : null
            )}
          </main>
        </>
      ) : (
        'loading'
      )}
    </>
  );
};

export default Home;
